name: Daily News Collection

on:
  schedule:
    # Moscow is UTC+3, so 16:28 Moscow time is 13:28 UTC
    - cron: '28 13 * * *'  # Runs at 16:28 Moscow time (UTC+3)
  workflow_dispatch:  # Allows manual trigger for testing

permissions:
  contents: read
  actions: write

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create env file
        run: |
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > .env
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
          echo "CELERY_BROKER_URL=redis://redis:6379/0" >> .env
          echo "CELERY_RESULT_BACKEND=redis://redis:6379/0" >> .env

      - name: Start containers
        run: docker compose up -d redis celery_worker

      - name: Wait for services
        run: sleep 10

      - name: Run news collection task
        run: |
          docker compose exec -T celery_worker python -c "
          from celery_app import fetch_and_send_news
          result = fetch_and_send_news.delay()
          print('Task started with ID:', result.id)
          "

      - name: Wait for task completion
        run: |
          # Wait for up to 5 minutes for task to complete
          timeout 300 bash -c '
          until docker compose logs celery_worker | grep -q "Successfully sent"; do
            echo "Waiting for task to complete..."
            sleep 10
          done
          '

      - name: Show logs
        if: always()
        run: docker compose logs

      - name: Stop containers
        if: always()
        run: docker compose down 