name: Test News Collection

on:
  workflow_dispatch:  # Manual trigger for testing

jobs:
  test-news-fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create env file
        run: |
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > .env
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
          echo "CELERY_BROKER_URL=redis://redis:6379/0" >> .env
          echo "CELERY_RESULT_BACKEND=redis://redis:6379/0" >> .env

      - name: Start containers
        run: docker compose up -d

      - name: Run for test period
        run: |
          echo "Running for 5 minutes..."
          sleep 300  # Run for 5 minutes

      - name: Show logs
        if: always()
        run: docker compose logs

      - name: Stop containers
        if: always()
        run: docker compose down 